language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-mirage.sh
script: bash -ex .travis-mirage.sh && bash -ex .travis-mirage-deploy.sh
sudo: required
dist: trusty
env:
  matrix:
  - OCAML_VERSION=4.07 MIRAGE_BACKEND=unix FLAGS="-vv --net socket"
  - OCAML_VERSION=4.07 MIRAGE_BACKEND=unix FLAGS="-vv --net direct"
  - OCAML_VERSION=4.07 MIRAGE_BACKEND=xen  DEPLOY=1 XENIMG="openmirageorg"
    PINS="travis-senv:https://github.com/hannesm/travis-senv.git#fix"
    FLAGS="-vv --net direct --dhcp false --ipv4 46.43.42.135/28
    --ipv4-gateway 46.43.42.129
    --host openmirage.org --redirect https://mirage.io"
  - OCAML_VERSION=4.07 MIRAGE_BACKEND=xen DEPLOY=1 XENIMG="mirageio"
    PINS="travis-senv:https://github.com/hannesm/travis-senv.git#fix"
    FLAGS="-vv --net direct --dhcp false --ipv4 46.43.42.136/28
    --ipv4-gateway 46.43.42.129 --tls true
    --secrets-kv_ro fat --host mirage.io"
  global:
  - UPDATE_GCC_BINUTILS=1
  - SRC_DIR=./src
  - secure: PUu3+Enupf9jcIPD/hs5b6zrNuJagTDXJGtYfSUIFvzevSXZzs6mXPu8L2vvAQbQ8ig/8VLToa44vUTG9OEy9SxXrR6yTQGfj4YxJ5BXKHwhYMTBXnR1e+S1gA4a5tilMa7M/a0hWa1rORv3diMIK3dihjc1m6VzpCK/4vly7KU=
  - secure: crnwZ3MDUA9szI/EuwB9o7plXVF2QCx+JpOazy4SwC2v47Vf5voOEAxh7iFMgGziBqzKGVnDw4/37WHVm5vdgaL4lL2T73F1PqXbiCdhhwZVcf+EAXr8KmoaNXRieL7qPsemQVvPWUiERZRmR2okvm60EqifZA9/dy/48dJIGMI=
  - secure: JijSTl0jOOPL0HoWooCBnhokjqboQSgwy3orgG5nUIPrluthNjix4ujds9TOuEtv2pflbgptUUdYJ7R6VfeZk/UWIVUbwBRjtMJRQRDPB0jxyoL9VLGzTwfdovwV0Rg0jeJkBWsAJjIxkdawE2R4wexAOn/tWDiLaSQh/n096Fc=
  - secure: DUOpC7WiKJHWNcWdlB2T3oQd43p52pGwFOaGX1B9KxYdObnOOScLyMrbVBLl7Y47HHLU1UbgZ1WuilI/ezK2G/pAuq7WLHF9wVw6QyJhiRwhGSFOCKOeScU8LE6Pw4AnKyTDDKL/IY2D94IfcI/db2NI6uzB2rtdVwkqI0f8+4I=
  - secure: dKlWRe8xZmBfg2ZgBiET2KqA+pvrKZHwvqnpm304Fojpyw2C+lEDUo6DQOLEThDeih28FOU3rlUCtxasJQpDWw52CRseXYVqaX2UuNzvmv8TqrVXTxv/gZgpM50xCKCRCDEEgznH7hby1z34MxrUAEMDd4LkQXKjr8sv2aH0FNA=
  - secure: TFOc5f/EA7WROfKW/tZZJbRr+HVjojRvmjGvXTO1BPec0/bBS0khAD8ozd1v938lIN0f81P26ZMcQlvsBB+EFfo7yZyYztmBAAPSaKaMu87aYi/pzEr7oNL8I8UlV0Rri1SHAEOKKoF9s9M4dYDxhXNbIuoCpnN89sXld2nk4fE=
  - secure: BJJDKHqZfZWTk3Wf0osT1NOHb50BLMjA+iSaftwH2HsBhtGT2BpvqFq34p2HE2mv/+2QB2a/A4ajj1ePMw03SqD83X4DjYCUh73Pc1PYbqEJ1kL6ivaGC7gxVbT/2WtPxXPGnCZ0sooMY/CQWrlx5PMWZZtxHQootkZ6XpKOsWM=
  - secure: cZpbGeWcGCicdY1pyBuGaioaK9eh/KixqrKcaaqH8I3IWbLthDdwSNVNjcXO67kIb6jXA6/6TX7E5xxTQe80LbIuarNSLJvtqnh1A9yppVA3SYQI7sY8hjk8uolm+qnAtEZKxlUl/T5zxFmokP6MKp7wDUZJPSk3JiN0xwuzhuc=
  - secure: aZ71DJ4wXOZcdVoMSJvWg2hSMJrTczbb/ZNZISrj3dcgLojnsX1s/1tlVovNetDzKLlW4gdQIO/PgOL5z6dZRS/IJvZvPrUKWtkt6R2xKnnQU+fgeziIfltN7rXMT4GFcSaJHl6S53XnnnCMqkc2jjhmxEt36xwVr1yU7onM6gE=
  - secure: EuanehUlVIL/qJLD0j4CfbqDW0MIKbIVu2aRwwbbNK2LgQtr/kDJSVrtwEEFddOxC2ZmbGxmUC4TCZ6yFlpfQkr6UnyYmnINb/EL2ocvay6/PAFXcDRtCNWd7MzfiUfTIPxg7qwYBqabgdJ/iKlRrFgHOeSts3OhBZs4MzD62GY=
  - secure: Juipi/OO05oERAttsFLSow5M1P8YPb3vigGgufaedSI5KjzcPrU6PeKtX6D7nHCbzjZEIj3uRnv9VC8eT46JC7IYQs4ATGnEQnJsGoE2gHWQ348UlK7o/jgPtG9XeYaTgxN4N/hOKk/B08MIJwsJllUUZvBztUIJlUddrFOt0xE=
  - secure: Qq8YWXsJk3R0EJIMnT7cScCp8xDAG5z3Q2seA8d8P2LaR/1FvHkZGUMXwJ27f1ZvOmtBCEhcXbYtYFfedXJwy4JGRWq165te20XZS0gqpdi5DHbv0S1rlE01bdcQFVQSvxeMXsO+KdUmrx9+yjG1r4CarB+m5CpHHJdIs9mxb/c=
  - secure: dIRmXAwM8EVjni3k0POewi0eMXB7Ebr/sTJhYPUYA31TrW98OYO6P2VCR4zND5e7ObmM1pyjXlsP/i6Q8YTch3xxJgBeYOCbsb7BfJ62UioGdWL2E5wlrnDPgHxdPayDajRgmxRjY6EErAfaFv+Kk2OmeeIv4ibfMoMzSGjQT+A=
